# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/XADC_PS/XADC_PS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS || ORIG_REF_NAME==XADC_PS} -quiet] -quiet

# IP: bd/XADC_PS/ip/XADC_PS_processing_system7_0_0/XADC_PS_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS_processing_system7_0_0 || ORIG_REF_NAME==XADC_PS_processing_system7_0_0} -quiet] -quiet

# IP: bd/XADC_PS/ip/XADC_PS_xadc_wiz_0_0/XADC_PS_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS_xadc_wiz_0_0 || ORIG_REF_NAME==XADC_PS_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/XADC_PS/ip/XADC_PS_ps7_0_axi_periph_0/XADC_PS_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS_ps7_0_axi_periph_0 || ORIG_REF_NAME==XADC_PS_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/XADC_PS/ip/XADC_PS_rst_ps7_0_100M_0/XADC_PS_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS_rst_ps7_0_100M_0 || ORIG_REF_NAME==XADC_PS_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/XADC_PS/ip/XADC_PS_xbar_0/XADC_PS_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS_xbar_0 || ORIG_REF_NAME==XADC_PS_xbar_0} -quiet] -quiet

# IP: bd/XADC_PS/ip/XADC_PS_auto_pc_0/XADC_PS_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS_auto_pc_0 || ORIG_REF_NAME==XADC_PS_auto_pc_0} -quiet] -quiet

# IP: bd/XADC_PS/ip/XADC_PS_xfft_0_0/XADC_PS_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS_xfft_0_0 || ORIG_REF_NAME==XADC_PS_xfft_0_0} -quiet] -quiet

# IP: bd/XADC_PS/ip/XADC_PS_xlconstant_0_0/XADC_PS_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS_xlconstant_0_0 || ORIG_REF_NAME==XADC_PS_xlconstant_0_0} -quiet] -quiet

# IP: bd/XADC_PS/ip/XADC_PS_xlconstant_0_1/XADC_PS_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS_xlconstant_0_1 || ORIG_REF_NAME==XADC_PS_xlconstant_0_1} -quiet] -quiet

# IP: bd/XADC_PS/ip/XADC_PS_axi_dma_0_0/XADC_PS_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS_axi_dma_0_0 || ORIG_REF_NAME==XADC_PS_axi_dma_0_0} -quiet] -quiet

# IP: bd/XADC_PS/ip/XADC_PS_axi_smc_0/XADC_PS_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_PS_axi_smc_0 || ORIG_REF_NAME==XADC_PS_axi_smc_0} -quiet] -quiet

# XDC: bd/XADC_PS/XADC_PS_ooc.xdc
