# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Twaga/ECE421/XADC_DMA_FFT/XADC_PS.srcs/sources_1/bd/XADC_PS/ip/XADC_PS_xbar_0/XADC_PS_xbar_0.xci
# IP: The module: 'XADC_PS_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Twaga/ECE421/XADC_DMA_FFT/XADC_PS.srcs/sources_1/bd/XADC_PS/ip/XADC_PS_xbar_0/XADC_PS_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XADC_PS_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Twaga/ECE421/XADC_DMA_FFT/XADC_PS.srcs/sources_1/bd/XADC_PS/ip/XADC_PS_xbar_0/XADC_PS_xbar_0.xci
# IP: The module: 'XADC_PS_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Twaga/ECE421/XADC_DMA_FFT/XADC_PS.srcs/sources_1/bd/XADC_PS/ip/XADC_PS_xbar_0/XADC_PS_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XADC_PS_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
