# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Lab02/Lab02.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab02 || ORIG_REF_NAME==Lab02} -quiet] -quiet

# IP: bd/Lab02/ip/Lab02_processing_system7_0_0/Lab02_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab02_processing_system7_0_0 || ORIG_REF_NAME==Lab02_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab02/ip/Lab02_axi_gpio_0_0/Lab02_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab02_axi_gpio_0_0 || ORIG_REF_NAME==Lab02_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Lab02/ip/Lab02_axi_gpio_0_1/Lab02_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab02_axi_gpio_0_1 || ORIG_REF_NAME==Lab02_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Lab02/ip/Lab02_xbar_0/Lab02_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab02_xbar_0 || ORIG_REF_NAME==Lab02_xbar_0} -quiet] -quiet

# IP: bd/Lab02/ip/Lab02_ps7_0_axi_periph_0/Lab02_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab02_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab02_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab02/ip/Lab02_rst_ps7_0_100M_0/Lab02_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab02_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab02_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Lab02/ip/Lab02_auto_pc_0/Lab02_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab02_auto_pc_0 || ORIG_REF_NAME==Lab02_auto_pc_0} -quiet] -quiet

# XDC: bd/Lab02/Lab02_ooc.xdc
